### ISSUE TITLE
Unable to access jarfile quilt-server-launch.jar

### ISSUE THREAD

**Issue by Heus-Sueh** [Theslees/Termux-minecraft-server-installer#6]
when i do the `mc` command it gives this error
![image](https://github.com/Theslees/Termux-minecraft-server-installer/assets/98482469/820f5384-38cb-4958-a194-71e74d8adfd7)

**Comment by Theslees** [comment]
Hello, 

Did you change the name of the folder your server's located in? Run `install.sh` again  (if you did) to update `mc`, or modify `/usr/bin/mc` (for root) with your text editor to point it to your new folder.

**Comment by Heus-Sueh** [comment]
Sorry for the delay in responding, the mc executable is pointing to the right folder: cd /root/Heus_World && java -Xms1024M -Xmx1024M -

> Hello,
> 
> Did you change the name of the folder your server's located in? Run `install.sh` again (if you did) to update `mc`, or modify `/usr/bin/mc` (for root) with your text editor to point it to your new folder.

Sorry for the delay in responding, the `mc` executable is pointing to the right folder:
![image](https://github.com/Theslees/Termux-minecraft-server-installer/assets/98482469/f642978b-1b42-4b98-8dce-62d61217f2af)

the error that appears when running is this:
![image](https://github.com/Theslees/Termux-minecraft-server-installer/assets/98482469/d613f430-d2cf-4138-ae76-a42ac050ff4a)

**Comment by Theslees** [comment]
Oh I see, can you also confirm if that quilt server launch jar is in the directory u pointed it to aswell?

I'm going to pushout an update to change where it grabs the installer from, and rewrite the 'mc' script it places in your bin folder (since i dont like the method I used here)

Hopefully that'll fix your issue if this comment does not help.. I know some mods need updating aswell :P

Let me know *

**Comment by Heus-Sueh** [comment]
> I'm going to pushout an update to change where it grabs the installer from, and rewrite the 'mc' script it places in your bin folder (since i dont like the method I used here)
> Hopefully that'll fix your issue if this comment does not help.. I know some mods need updating aswell :P

thanks :+1: 
> Oh I see, can you also confirm if that quilt server launch jar is in the directory u pointed it to aswell?

the quilt appears to be in the config folder
![image](https://github.com/Theslees/Termux-minecraft-server-installer/assets/98482469/f1d45d06-879c-4d07-9d79-168726ff1e53)

I wanted to create a vanilla server, is there a way to do that or is this script just for the quilt itself?

**Comment by Theslees** [comment]
Hey,
If you're still stuck on this, I encourage you to update with `git pull&&git fetch -q`, i rewrote the way my script grabs the quilt server instance installer.

Though if you're done with this I understand, I just want to check what's been causing this and if I fixed it so I can mark this issue as resolved.

If it didn't fix anything please let me know what distro you're using,  I'd appriciate it alot, Thanks :P

P.S The installer downloads and unpacks a *bare-bones MC java server instance, powered by quilt*, so its vanilla. The option to add any fabric/quilt mod is available and can be done by dropping the jars for those loaders in `mods/`

**Comment by Heus-Sueh** [comment]
the distro I'm using is arch linux, I deleted all the files and updated the script but now the installer.sh is not able to make the executable mc, it's giving this problem:

`./install.sh: line 222: /data/data/com.termux/files/usr/bin: Is a directory`
![image](https://user-images.githubusercontent.com/98482469/253823991-58415082-3d1a-4804-b50c-e7430e773f0e.png)
